'use strict';

// Export web by default. Other platforms have custom index.[platform].js files
var {
  VictoryArea,
  VictoryAxis,
  VictoryBar,
  VictoryCandlestick,
  VictoryChart,
  VictoryErrorBar,
  VictoryGroup,
  VictoryLine,
  VictoryPie,
  VictoryPolarAxis,
  VictoryScatter,
  VictoryStack,
  VictoryVoronoi,
  VictoryContainer,
  VictoryBrushContainer,
  VictoryCursorContainer,
  VictorySelectionContainer,
  VictoryVoronoiContainer,
  VictoryZoomContainer,
  VictoryAnimation,
  VictoryClipContainer,
  VictoryLabel,
  VictoryLegend,
  VictoryPortal,
  VictoryPrimitives,
  VictorySharedEvents,
  VictoryTheme,
  VictoryTooltip,
  VictoryTransition
} = require('victory');

module.exports = {
  VictoryArea,
  VictoryAxis,
  VictoryBar,
  VictoryCandlestick,
  VictoryChart,
  VictoryErrorBar,
  VictoryGroup,
  VictoryLine,
  VictoryPie,
  VictoryPolarAxis,
  VictoryScatter,
  VictoryStack,
  VictoryVoronoi,
  VictoryContainer,
  VictoryBrushContainer,
  VictoryCursorContainer,
  VictorySelectionContainer,
  VictoryVoronoiContainer,
  VictoryZoomContainer,
  VictoryAnimation,
  VictoryClipContainer,
  VictoryLabel,
  VictoryLegend,
  VictoryPortal,
  VictoryPrimitives,
  VictorySharedEvents,
  VictoryTheme,
  VictoryTooltip,
  VictoryTransition
}
